In [2]:
import pandas as pd
import csv

We will be workind to modify a spreadsheet for Lee.

In [24]:
df_original = pd.read_excel('lees_spreadsheet.xlsx', sheet_name='Sheet1')
df_original.info()
df_original.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1209 entries, 0 to 1208
Data columns (total 4 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   2025/04/12 07:02:2025/04/13 06:49  1209 non-null   object
 1   [Date - MeSH]                      1193 non-null   object
 2   Unnamed: 2                         0 non-null      float64
 3   Sort by: Most Recent               1179 non-null   object
dtypes: float64(1), object(3)
memory usage: 37.9+ KB

Index(['2025/04/12 07:02:2025/04/13 06:49', '[Date - MeSH]', 'Unnamed: 2',
       'Sort by: Most Recent'],
      dtype='object')

The result Lee wanted was to have only the unique rows show up.

In [29]:
cols = df_original.columns
print(cols)
cols1 = [col for col in cols if 'Unnamed' not in col]
print(cols1)
df_w = df_original[cols1]
df_w.head()

Index(['2025/04/12 07:02:2025/04/13 06:49', '[Date - MeSH]', 'Unnamed: 2',
       'Sort by: Most Recent'],
      dtype='object')
['2025/04/12 07:02:2025/04/13 06:49', '[Date - MeSH]', 'Sort by: Most Recent']

   2025/04/12 07:02:2025/04/13 06:49  [Date - MeSH]  Sort by: Most Recent
0  2025/04/12 07:02:2025/04/13 06:49  [Date - MeSH]  Sort by: Most Recent
1                              abies   [All Fields]                    OR
2                              abies   [All Fields]                    OR
3                              abies   [MeSH Terms]                    OR
4                              abies   [MeSH Terms]                    OR

In [31]:
df_wo = df_w[cols[:2]]
df_wo.head()

   2025/04/12 07:02:2025/04/13 06:49  [Date - MeSH]
0  2025/04/12 07:02:2025/04/13 06:49  [Date - MeSH]
1                              abies   [All Fields]
2                              abies   [All Fields]
3                              abies   [MeSH Terms]
4                              abies   [MeSH Terms]

We are going to accomplish this by forming the set of tuples generated by the rows.

In [32]:
unique_rows_wo = set()
for row in df_wo.itertuples():
    row_tuple = (row[1], row[2])
    if row_tuple not in unique_rows_wo:
        unique_rows_wo.add(row_tuple)

print(len(unique_rows_wo))
print(len(df_wo))
# Save the unique rows to a new Excel file
df_unique = pd.DataFrame(list(unique_rows_wo), columns=[list(cols[:2])])
df_unique.to_excel('unique_rows_wo.xlsx', index=False)

289
1209

In [34]:
unique_rows_w = set()
for row in df_w.itertuples():
    row_tuple = (row[1], row[2])
    if row_tuple not in unique_rows_w:
        unique_rows_w.add(row_tuple)

print(len(unique_rows_w))
print(len(df_w))
# Save the unique rows to a new Excel file
df_unique = pd.DataFrame(list(unique_rows_w), columns=[list(cols1)])
df_unique.to_excel('unique_rows_w.xlsx', index=False)

289
1209

ValueError: 3 columns passed, passed data had 2 columns